services:
  postgres:
    image: postgres:16
    container_name: jcj_postgres
    environment:
      POSTGRES_USER: jcj
      POSTGRES_PASSWORD: jcjpassword
      POSTGRES_DB: jcjdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: jcj_redis
    ports:
      - "6379:6379"

  chroma:
    image: chromadb/chroma:latest
    container_name: jcj_chroma
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma

  backend:
    env_file:
      - .env
    build: ./backend
    container_name: jcj_backend
    environment:
      - DATABASE_URL=postgresql+psycopg://jcj:jcjpassword@postgres:5432/jcjdb
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_URL=http://chroma:8000
      - AI_PROVIDER=${AI_PROVIDER:-groq}
      - AI_MODEL=${AI_MODEL:-llama-3.3-70b-versatile}
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - chroma
    volumes:
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
      - ./data:/app/data
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

  frontend:
    build: ./frontend
    container_name: jcj_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"

  worker:
    env_file:
      - .env
    build: ./backend
    container_name: jcj_worker
    environment:
      - DATABASE_URL=postgresql+psycopg://jcj:jcjpassword@postgres:5432/jcjdb
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_URL=http://chroma:8000
      - AI_PROVIDER=${AI_PROVIDER:-groq}
      - AI_MODEL=${AI_MODEL:-llama-3.3-70b-versatile}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - postgres
      - redis
      - chroma
    volumes:
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
      - ./data:/app/data
    command: >
      sh -lc "PYTHONPATH=/app rq worker jcj"


volumes:
  postgres_data:
  chroma_data:
  frontend_node_modules:
